# This action installs dependencies for Qt on Ubuntu
# It does not install any Qt-Python wrapper.

name: 'Install Ubuntu packages for Qt'
description: 'This action should only be run on Ubuntu'
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install qtbase5-dev
        sudo apt-get install qtchooser
        sudo apt-get install qt5-qmake
        sudo apt-get install qtbase5-dev-tools
        sudo apt-get install libegl1
        sudo apt-get install libxkbcommon-x11-0
        sudo apt-get install libxcb-icccm4
        sudo apt-get install libxcb-image0
        sudo apt-get install libxcb-keysyms1
        sudo apt-get install libxcb-randr0
        sudo apt-get install libxcb-render-util0
        sudo apt-get install libxcb-xinerama0
        sudo apt-get install libxcb-shape0
        sudo apt-get install pulseaudio
        sudo apt-get install libpulse-mainloop-glib0
        # Needed to work around https://bugreports.qt.io/browse/PYSIDE-1547
        sudo apt-get install libopengl0
        # Needed for Qt6 video playback
        sudo apt-get install libgstreamer-gl1.0-0
      shell: bash
