# This action installs dependencies for Qt on Ubuntu
# It does not install any Qt-Python wrapper.

name: 'Install Ubuntu packages for Qt'
description: 'This action should only be run on Ubuntu'
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install qt5-default
        sudo apt-get install libxkbcommon-x11-0
        sudo apt-get install libxcb-icccm4
        sudo apt-get install libxcb-image0
        sudo apt-get install libxcb-keysyms1
        sudo apt-get install libxcb-randr0
        sudo apt-get install libxcb-render-util0
        sudo apt-get install libxcb-xinerama0
        sudo apt-get install pulseaudio
        sudo apt-get install libpulse-mainloop-glib0
      shell: bash
