# This workflow installs dependencies from master

name: ETS from source

on:
  schedule:
    - cron:  '0 0 * * 4'

jobs:
  test:
    env:
      # Enforce selection of toolkit
      ETS_TOOLKIT: qt
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolkit: ['pyside2']
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Qt dependencies for Linux
        uses: ./.github/actions/apt-get-qt-deps
        if: startsWith(matrix.os, 'ubuntu')
      - name: Install local packages
        run: python -m pip install .[${{ matrix.toolkit }},editors,test]
      - name: Install source dependencies
        run: |
          python -m pip install --force-reinstall git+http://github.com/enthought/pyface.git#egg=pyface
          python -m pip install --force-reinstall git+http://github.com/enthought/traits.git#egg=traits
      - name: Sanity check dependencies
        run: python -m pip list
      - name: Run test suite
        uses: GabrielBB/xvfb-action@v1
        with:
          run: python -m unittest discover -v traitsui
          working-directory: ${{ runner.temp }}
