# This workflow runs integration tests (e.g. demo examples), which requires
# more dependencies


name: Integration tests

on: pull_request
  #schedule:
  #  - cron:  '0 0 * * 4'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolkit: ['pyside2']
        # Dependencies include chaco/enable, whose installation fails
        # on Python 3.8 and 3.9
        python-version: [3.6]
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Qt dependencies for Linux
        uses: ./.github/actions/apt-get-qt-deps
        if: startsWith(matrix.os, 'ubuntu')
      - name: Install Swig 3.0.12
        # Dependencies include enable, which has known issue with swig 4.0
        # see enthought/enable#360
        run: sudo apt-get install swig=3.0.12
        if: startsWith(matrix.os, 'ubuntu')
      - name: Install Python packages and dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[${{ matrix.toolkit }},test,editors]
          python -m pip install .[examples]
      - name: Run integration tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: python -m unittest discover -v ${{ github.workspace }}/integrationtests
          working-directory: ${{ runner.temp }}
