# This workflow targets stable released dependencies from EDM.
# Note that some packages may not actually be installed from EDM but from
# PyPI, see etstool.py implementations.

# wxPython should be included but it isn't because the test suite is currently
# failing on all platforms and GitHub Actions does not support allow-failure
# yet (see actions/toolkit#399)

name: Test with EDM

on: [workflow_dispatch]

env:
  INSTALL_EDM_VERSION: 3.5.0
  QT_MAC_WANTS_LAYER: 1

jobs:

  # Test against EDM packages on Windows and OSX
  test-with-edm:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolkit: ['pyqt5', 'pyside2', 'pyside6']
        python-version: ['3.8']
        include:
          - os: ubuntu-latest
            toolkit: 'null'
            python-version: '3.8'
        exclude:
          - os: windows-latest
            toolkit: pyside6
          - toolkit: 'pyqt5'
            python-version: '3.8'
          - toolkit: 'pyside2'
            python-version: '3.8'
    runs-on: ${{ matrix.os }}
    env:
      # Set root directory, mainly for Windows, so that the EDM Python
      # environment lives in the same drive as the cloned source. Otherwise
      # 'pip install' raises an error while trying to compute
      # relative path between the site-packages and the source directory.
      EDM_ROOT_DIRECTORY: ${{ github.workspace }}/.edm
      # set the font config path for linux
      FONTCONFIG_PATH: /etc/fonts
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt dependencies for Linux
        uses: ./.github/actions/install-qt-support
        if: startsWith(matrix.os, 'ubuntu') && matrix.toolkit != 'wx' && matrix.toolkit != 'null'
      - name: Cache EDM packages
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.toolkit }}-${{ hashFiles('etstool.py') }}
      - name: Setup EDM
        uses: enthought/setup-edm-action@v2
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Install click to the default EDM environment
        run: edm install -y wheel click coverage
      - name: Install test environment
        run: edm run -- python etstool.py install --toolkit=${{ matrix.toolkit }} --runtime=${{ matrix.python-version }}
      - name: Run the test suite (Linux)
        run: xvfb-run -a edm run -- python etstool.py test --toolkit=${{ matrix.toolkit }} --runtime=${{ matrix.python-version }}
        if: matrix.os == 'ubuntu-latest'
      - name: Run the test suite (Windows/macOS)
        run: edm run -- python etstool.py test --toolkit=${{ matrix.toolkit }} --runtime=${{ matrix.python-version }}
        if: matrix.os != 'ubuntu-latest'
