name: Test documentation build

on:
  pull_request

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies and local packages
      run: python -m pip install .[docs,pyside6]
    - name: Autogenerate API documentation
      run: |
        sphinx-apidoc -e -M --no-toc -o docs/source/api traitsui
    - name: Build HTML documentation with Sphinx
      run: |
        python -m sphinx -b html -W source build
      working-directory: docs
