name: Doc build

on:
  pull_request

jobs:
  docs:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and local packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install sphinx enthought-sphinx-theme
        python -m pip install .
    - name: Build HTML documentation with Sphinx
      run: |
        cd docs
        sphinx-apidoc -e -M --no-toc -o source/api traitsui traitsui/qt4/* traitsui/wx/* */tests
        sphinx-build -b html -d build/doctrees source build/html
