# This workflow targets stable released dependencies from EDM.
# Note that some packages may not actually be installed from EDM but from
# PyPI, see etstool.py implementations.

# wxPython should be included but it isn't because the test suite is currently
# failing on all platforms and GitHub Actions does not support allow-failure
# yet (see actions/toolkit#399)

name: Test with EDM

on: pull_request

env:
  INSTALL_EDM_VERSION: 3.2.3

jobs:

  # Test against EDM packages on Windows and OSX
  test-with-edm:
    strategy:
      matrix:
        os: [windows-latest]
        toolkit: ['pyqt5', 'pyside2']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache EDM packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ matrix.toolkit }}-${{ hashFiles('etstool.py') }}
      - name: Setup EDM
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Install click to the default EDM environment
        run: edm install -y wheel click coverage
      - name: Install test environment
        run: edm run -- python etstool.py install --toolkit=${{ matrix.toolkit }}
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: edm run -- python etstool.py test --toolkit=${{ matrix.toolkit }}
