# This workflow targets stable released dependencies from PyPI
# The matrix is conservative to avoid using too much public resources.

name: Test with PyPI

on:
  schedule:
    - cron:  '0 3 * * 4'
  # Make it possible to manually trigger the workflow
  workflow_dispatch:

jobs:
  # Tests against Qt/Python packages from PyPI
  pip-qt:
    env:
      # Enforce selection of toolkit
      ETS_TOOLKIT: qt
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolkit: ['pyside2']
        python-version: [3.6]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Qt dependencies for Linux
        uses: ./.github/actions/apt-get-qt-deps
        if: startsWith(matrix.os, 'ubuntu')
      - name: Update pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install local packages
        run: python -m pip install .[${{ matrix.toolkit }},editors,test]
      - name: Run test suite
        uses: GabrielBB/xvfb-action@v1
        with:
          run: python -m unittest discover -v traitsui
          working-directory: ${{ runner.temp }}

  # Tests against wxPython from PyPI
  # On OSX:
  #   - wxPython complains about 'This program needs access to the screen'.
  # On Ubuntu:
  #   - For wxPython 4.0, we need libsdl-image1.2
  #   - For wxPython 4.1, we need libsdl2-2.0-0
  #   - The Ubuntu build can be run but it fails and there are no equivalence
  #     of allow-failure on GitHub Actions.
  pip-wx:
    env:
      # Enforce selection of toolkit
      ETS_TOOLKIT: wx
    strategy:
      # Test failure is currently expected to fail on Ubuntu
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.6]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install local packages
        run: python -m pip install .[wx,editors,test]
      - name: Run test suite
        uses: GabrielBB/xvfb-action@v1
        with:
          run: python -m unittest discover -v traitsui
          working-directory: ${{ runner.temp }}

  notify-on-failure:
    needs: [pip-qt, pip-wx]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack channel on failure
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.ETS_BOTS_SLACK_CHANNEL_ID }}
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_ACTION_SECRET }}

  notify-on-success:
    needs: [pip-qt, pip-wx]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack channel on success
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.ETS_BOTS_SLACK_CHANNEL_ID }}
          status: SUCCESS
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_ACTION_SECRET }}
