# This workflow targets stable released dependencies from EDM.
# Note that some packages may not actually be installed from EDM but from
# PyPI, see etstool.py implementations.

name: Test with EDM

on: push

env:
  INSTALL_EDM_VERSION: 3.2.1

jobs:

  # Test against EDM packages on Linux
  # wxPython is excluded because the test suite is currently failing on Ubuntu
  # and GitHub Actions does not support allow-failure yet
  # (see actions/toolkit#399)
  test-edm-linux:
    strategy:
      matrix:
        toolkit: ['null', 'pyqt', 'pyqt5', 'pyside2', 'wx']
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install libxkbcommon-x11-0
        if: matrix.toolkit != 'wx'
      - name: Install Wx dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-2.0-0
        if: matrix.toolkit == 'wx'
      - name: Install GL dependencies for Linux
        run: sudo apt-get install libglu1-mesa-dev
      - name: Cache EDM packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ matrix.toolkit }}-${{ hashFiles('etstool.py') }}
      - name: Setup EDM
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Install click to the default EDM environment
        run: edm --config ci/.edm.yaml install -y wheel click coverage
      - name: Install test environment
        run: edm run -- python etstool.py install --toolkit=${{ matrix.toolkit }}
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: edm run -- python etstool.py test --toolkit=${{ matrix.toolkit }}

  # Test against EDM packages on Windows and OSX
  test-with-edm:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        toolkit: ['pyqt', 'pyqt5', 'pyside2', 'wx']
    runs-on: ${{ matrix.os }}
    env:
      # Set root directory, mainly for Windows, so that the EDM Python
      # environment lives in the same drive as the cloned source. Otherwise
      # 'pip install' raises an error while trying to compute
      # relative path between the site-packages and the source directory.
      EDM_ROOT_DIRECTORY: ${{ github.workspace }}/.edm
    steps:
      - uses: actions/checkout@v2
      - name: Cache EDM packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ matrix.toolkit }}-${{ hashFiles('etstool.py') }}
      - name: Setup EDM
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Install click to the default EDM environment
        run: edm --config ci/.edm.yaml install -y wheel click coverage
      - name: Install test environment
        run: edm run -- python etstool.py install --toolkit=${{ matrix.toolkit }}
      - name: Run tests
        run: edm run -- python etstool.py test --toolkit=${{ matrix.toolkit }}
